import re
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(881, 667)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 881, 651))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.searchLineEdit = QtWidgets.QLineEdit(self.tab)
        self.searchLineEdit.setGeometry(QtCore.QRect(20, 40, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.searchLineEdit.setFont(font)
        self.searchLineEdit.setText("")
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.dbRadioButton = QtWidgets.QRadioButton(self.tab)
        self.dbRadioButton.setGeometry(QtCore.QRect(170, 10, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dbRadioButton.setFont(font)
        self.dbRadioButton.setChecked(True)
        self.dbRadioButton.setObjectName("dbRadioButton")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(20, 80, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.nameLineEdit = QtWidgets.QLineEdit(self.tab)
        self.nameLineEdit.setGeometry(QtCore.QRect(20, 110, 811, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nameLineEdit.setFont(font)
        self.nameLineEdit.setReadOnly(True)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.webRadioButton = QtWidgets.QRadioButton(self.tab)
        self.webRadioButton.setGeometry(QtCore.QRect(330, 10, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.webRadioButton.setFont(font)
        self.webRadioButton.setObjectName("webRadioButton")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 150, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 10, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.originalTextEdit = QtWidgets.QTextEdit(self.tab)
        self.originalTextEdit.setEnabled(True)
        self.originalTextEdit.setGeometry(QtCore.QRect(20, 180, 811, 171))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.originalTextEdit.setFont(font)
        self.originalTextEdit.setReadOnly(True)
        self.originalTextEdit.setObjectName("originalTextEdit")
        self.prevCommandLinkButton = QtWidgets.QCommandLinkButton(self.tab)
        self.prevCommandLinkButton.setGeometry(QtCore.QRect(20, 580, 101, 41))
        self.prevCommandLinkButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.prevCommandLinkButton.setObjectName("prevCommandLinkButton")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 540, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.stemmedTextEdit = QtWidgets.QTextEdit(self.tab)
        self.stemmedTextEdit.setEnabled(True)
        self.stemmedTextEdit.setGeometry(QtCore.QRect(20, 390, 811, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stemmedTextEdit.setFont(font)
        self.stemmedTextEdit.setReadOnly(True)
        self.stemmedTextEdit.setObjectName("stemmedTextEdit")
        self.adStatusComboBox = QtWidgets.QComboBox(self.tab)
        self.adStatusComboBox.setGeometry(QtCore.QRect(190, 540, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.adStatusComboBox.setFont(font)
        self.adStatusComboBox.setObjectName("adStatusComboBox")
        self.adStatusComboBox.addItem("")
        self.adStatusComboBox.addItem("")
        self.adStatusComboBox.addItem("")
        self.nextCommandLinkButton = QtWidgets.QCommandLinkButton(self.tab)
        self.nextCommandLinkButton.setGeometry(QtCore.QRect(700, 580, 131, 41))
        self.nextCommandLinkButton.setObjectName("nextCommandLinkButton")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(20, 360, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.unclassifiedOnlyCheckBox = QtWidgets.QCheckBox(self.tab)
        self.unclassifiedOnlyCheckBox.setGeometry(QtCore.QRect(630, 40, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.unclassifiedOnlyCheckBox.setFont(font)
        self.unclassifiedOnlyCheckBox.setObjectName("unclassifiedOnlyCheckBox")
        self.goPushButton = QtWidgets.QPushButton(self.tab)
        self.goPushButton.setGeometry(QtCore.QRect(490, 40, 71, 31))
        self.goPushButton.setObjectName("goPushButton")
        self.savePushButton = QtWidgets.QPushButton(self.tab)
        self.savePushButton.setGeometry(QtCore.QRect(350, 540, 131, 23))
        self.savePushButton.setObjectName("savePushButton")
        self.appCounterLabel = QtWidgets.QLabel(self.tab)
        self.appCounterLabel.setGeometry(QtCore.QRect(160, 590, 521, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.appCounterLabel.setFont(font)
        self.appCounterLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.appCounterLabel.setObjectName("appCounterLabel")
        self.originalWordCounterLabel = QtWidgets.QLabel(self.tab)
        self.originalWordCounterLabel.setGeometry(QtCore.QRect(100, 150, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.originalWordCounterLabel.setFont(font)
        self.originalWordCounterLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.originalWordCounterLabel.setObjectName("originalWordCounterLabel")
        self.originalWordCounterLabel_2 = QtWidgets.QLabel(self.tab)
        self.originalWordCounterLabel_2.setGeometry(QtCore.QRect(160, 360, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.originalWordCounterLabel_2.setFont(font)
        self.originalWordCounterLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.originalWordCounterLabel_2.setObjectName("originalWordCounterLabel_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(30, 580, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.originalTextEdit_2 = QtWidgets.QTextEdit(self.tab_2)
        self.originalTextEdit_2.setEnabled(True)
        self.originalTextEdit_2.setGeometry(QtCore.QRect(20, 40, 811, 171))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.originalTextEdit_2.setFont(font)
        self.originalTextEdit_2.setReadOnly(False)
        self.originalTextEdit_2.setObjectName("originalTextEdit_2")
        self.stemmedTextEdit_2 = QtWidgets.QTextEdit(self.tab_2)
        self.stemmedTextEdit_2.setEnabled(True)
        self.stemmedTextEdit_2.setGeometry(QtCore.QRect(20, 250, 811, 111))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stemmedTextEdit_2.setFont(font)
        self.stemmedTextEdit_2.setReadOnly(True)
        self.stemmedTextEdit_2.setObjectName("stemmedTextEdit_2")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(20, 10, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(20, 220, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.stemmedTextEdit_3 = QtWidgets.QTextEdit(self.tab_2)
        self.stemmedTextEdit_3.setEnabled(True)
        self.stemmedTextEdit_3.setGeometry(QtCore.QRect(20, 410, 811, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stemmedTextEdit_3.setFont(font)
        self.stemmedTextEdit_3.setReadOnly(True)
        self.stemmedTextEdit_3.setObjectName("stemmedTextEdit_3")
        self.analyzePushButton = QtWidgets.QPushButton(self.tab_2)
        self.analyzePushButton.setGeometry(QtCore.QRect(710, 570, 121, 41))
        self.analyzePushButton.setObjectName("analyzePushButton")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(20, 380, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.statusLabel = QtWidgets.QLabel(self.tab_2)
        self.statusLabel.setGeometry(QtCore.QRect(190, 580, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.statusLabel.setFont(font)
        self.statusLabel.setObjectName("statusLabel")
        self.originalWordCounterLabel_3 = QtWidgets.QLabel(self.tab_2)
        self.originalWordCounterLabel_3.setGeometry(QtCore.QRect(100, 10, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.originalWordCounterLabel_3.setFont(font)
        self.originalWordCounterLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.originalWordCounterLabel_3.setObjectName("originalWordCounterLabel_3")
        self.originalWordCounterLabel_4 = QtWidgets.QLabel(self.tab_2)
        self.originalWordCounterLabel_4.setGeometry(QtCore.QRect(160, 220, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.originalWordCounterLabel_4.setFont(font)
        self.originalWordCounterLabel_4.setAlignment(QtCore.Qt.AlignCenter)
        self.originalWordCounterLabel_4.setObjectName("originalWordCounterLabel_4")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.analyzePushButton_2 = QtWidgets.QPushButton(self.tab_3)
        self.analyzePushButton_2.setGeometry(QtCore.QRect(550, 80, 121, 41))
        self.analyzePushButton_2.setObjectName("analyzePushButton_2")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(60, 30, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(170, 70, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(150, 110, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(130, 150, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.MetricLabel = QtWidgets.QLabel(self.tab_3)
        self.MetricLabel.setGeometry(QtCore.QRect(280, 30, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.MetricLabel.setFont(font)
        self.MetricLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.MetricLabel.setObjectName("MetricLabel")
        self.MetricLabel_2 = QtWidgets.QLabel(self.tab_3)
        self.MetricLabel_2.setGeometry(QtCore.QRect(280, 70, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.MetricLabel_2.setFont(font)
        self.MetricLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.MetricLabel_2.setObjectName("MetricLabel_2")
        self.MetricLabel_3 = QtWidgets.QLabel(self.tab_3)
        self.MetricLabel_3.setGeometry(QtCore.QRect(280, 110, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.MetricLabel_3.setFont(font)
        self.MetricLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.MetricLabel_3.setObjectName("MetricLabel_3")
        self.MetricLabel_4 = QtWidgets.QLabel(self.tab_3)
        self.MetricLabel_4.setGeometry(QtCore.QRect(280, 150, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.MetricLabel_4.setFont(font)
        self.MetricLabel_4.setAlignment(QtCore.Qt.AlignCenter)
        self.MetricLabel_4.setObjectName("MetricLabel_4")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dbRadioButton.setText(_translate("MainWindow", "Search in Database"))
        self.label_5.setText(_translate("MainWindow", "Name"))
        self.webRadioButton.setText(_translate("MainWindow", "Search on Google Play"))
        self.label_3.setText(_translate("MainWindow", "Description"))
        self.label.setText(_translate("MainWindow", "Search for apps:"))
        self.prevCommandLinkButton.setText(_translate("MainWindow", "Prev App"))
        self.label_2.setText(_translate("MainWindow", "Advertizement status:"))
        self.adStatusComboBox.setItemText(0, _translate("MainWindow", "Unknown"))
        self.adStatusComboBox.setItemText(1, _translate("MainWindow", "Advertiser-friendly"))
        self.adStatusComboBox.setItemText(2, _translate("MainWindow", "Not suitable for ads"))
        self.nextCommandLinkButton.setText(_translate("MainWindow", "Next App"))
        self.label_4.setText(_translate("MainWindow", "Stemmed description"))
        self.unclassifiedOnlyCheckBox.setText(_translate("MainWindow", "Show unclassified apps only"))
        self.goPushButton.setText(_translate("MainWindow", "Go"))
        self.savePushButton.setText(_translate("MainWindow", "Save"))
        self.appCounterLabel.setText(_translate("MainWindow", "App 0 of 0"))
        self.originalWordCounterLabel.setText(_translate("MainWindow", "(words: 0, characters: 0)"))
        self.originalWordCounterLabel_2.setText(_translate("MainWindow", "(words: 0, characters: 0)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Manual Classification"))
        self.label_6.setText(_translate("MainWindow", "Advertizement status:"))
        self.label_8.setText(_translate("MainWindow", "Description"))
        self.label_9.setText(_translate("MainWindow", "Stemmed description"))
        self.analyzePushButton.setText(_translate("MainWindow", "Analyze"))
        self.label_10.setText(_translate("MainWindow", "Vocabulary"))
        self.statusLabel.setText(_translate("MainWindow", "_"))
        self.originalWordCounterLabel_3.setText(_translate("MainWindow", "(words: 0, characters: 0)"))
        self.originalWordCounterLabel_4.setText(_translate("MainWindow", "(words: 0, characters: 0)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Automatic Prediction"))
        self.analyzePushButton_2.setText(_translate("MainWindow", "Calculate"))
        self.label_11.setText(_translate("MainWindow", "Accuracy classification score:"))
        self.label_12.setText(_translate("MainWindow", "Recall score:"))
        self.label_13.setText(_translate("MainWindow", "ROC AUC score:"))
        self.label_14.setText(_translate("MainWindow", "Average precision:"))
        self.MetricLabel.setText(_translate("MainWindow", "-"))
        self.MetricLabel_2.setText(_translate("MainWindow", "-"))
        self.MetricLabel_3.setText(_translate("MainWindow", "-"))
        self.MetricLabel_4.setText(_translate("MainWindow", "-"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Classification Metrics "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Сompression Сhart"))

class EventHandling_MainWindow:
    adStatuses = {
        0: None,
        1: '\x01',
        2: '\x00'
    }

    def __init__(self, mainWindow):  
        self.mainWindow = mainWindow
        self.mainWindow.goPushButton.clicked.connect(self.onGoClick)
        self.mainWindow.nextCommandLinkButton.clicked.connect(self.next)
        self.mainWindow.prevCommandLinkButton.clicked.connect(self.prev)
        self.mainWindow.savePushButton.clicked.connect(self.save)
        self.mainWindow.analyzePushButton.clicked.connect(self.onAnalyzeClick)
        self.mainWindow.analyzePushButton_2.clicked.connect(self.onCalculateMetricsClick)

    def onGoClick(self):
        self.mainWindow.nameLineEdit.setText('')
        self.mainWindow.originalTextEdit.setPlainText('')
        self.mainWindow.stemmedTextEdit.setPlainText('')

        searchStr = self.mainWindow.searchLineEdit.text()

        if (self.mainWindow.dbRadioButton.isChecked()):
            self.searcher = self.dbSearcher
        else:
            self.searcher = self.webSearcher

        if (self.searcher.search(searchStr, self.mainWindow.unclassifiedOnlyCheckBox.isChecked()) > 0):
            self.currentApp = self.searcher.apps[0]
            self.updateAppInfo(self.currentApp)

        self.mainWindow.appCounterLabel.setText("App {} of {}".format(self.searcher.currentAppIndex + 1, self.searcher.appsTotal))
       
    def updateAppInfo(self, app):                
        if app.stemmedDescription is None:
            app.stemmedDescription = self.stem(app.description)

        comboboxIndex = [key for key, value in self.adStatuses.items() if value == app.isAdvertizerFriendly][0]
        self.mainWindow.adStatusComboBox.setCurrentIndex(comboboxIndex)

        self.mainWindow.nameLineEdit.setText(app.name)
        self.mainWindow.originalTextEdit.setPlainText(self.currentApp.description)
        self.mainWindow.stemmedTextEdit.setPlainText(self.currentApp.stemmedDescription)
        
        words1 = len(re.findall(r'\w+', self.currentApp.description))
        words2 = len(re.findall(r'\w+', self.currentApp.stemmedDescription))

        self.mainWindow.originalWordCounterLabel.setText("(words: {}, characters: {})".format(words1, len(self.currentApp.description)))
        self.mainWindow.originalWordCounterLabel_2.setText("(words: {}, characters: {})".format(words2, len(self.currentApp.stemmedDescription)))

    def next(self):
        if self.searcher.appsTotal > 0:
            self.currentApp = self.searcher.next()
            self.updateAppInfo(self.currentApp)
            self.mainWindow.appCounterLabel.setText("App {} of {}".format(self.searcher.currentAppIndex + 1, self.searcher.appsTotal))
        
    def prev(self):
        if self.searcher.appsTotal > 0:
            self.currentApp = self.searcher.prev()
            self.updateAppInfo(self.currentApp)
            self.mainWindow.appCounterLabel.setText("App {} of {}".format(self.searcher.currentAppIndex + 1, self.searcher.appsTotal))
    
    def save(self):
        adStatus = self.adStatuses[self.mainWindow.adStatusComboBox.currentIndex()]
        self.currentApp.isAdvertizerFriendly = adStatus
        self.repo.updateOrInsert(self.currentApp)

    def onAnalyzeClick(self):
        textToAnalyze = self.mainWindow.originalTextEdit_2.toPlainText()
        result = self.analyze(textToAnalyze)
        self.mainWindow.statusLabel.setText("{} ({})".format(result.label, result.probalility))
        self.mainWindow.stemmedTextEdit_2.setPlainText(result.processedContent)
        self.mainWindow.stemmedTextEdit_3.setPlainText("\n".join(result.vocabulary))

        words1 = len(re.findall(r'\w+', textToAnalyze))
        words2 = len(re.findall(r'\w+', result.processedContent))

        self.mainWindow.originalWordCounterLabel_3.setText("(words: {}, characters: {})".format(words1, len(textToAnalyze)))
        self.mainWindow.originalWordCounterLabel_4.setText("(words: {}, characters: {})".format(words2, len(result.processedContent)))

    def onCalculateMetricsClick(self):
        metrics = self.calculateMetrics()
        self.mainWindow.MetricLabel.setText('{:{width}.{prec}f}%'.format(metrics.acuracy * 100.0, width=5, prec=2))
        self.mainWindow.MetricLabel_2.setText('{:{width}.{prec}f}%'.format(metrics.recall * 100.0, width=5, prec=2))
        self.mainWindow.MetricLabel_3.setText('{:{width}.{prec}f}%'.format(metrics.roc_auc * 100.0, width=5, prec=2))
        self.mainWindow.MetricLabel_4.setText('{:{width}.{prec}f}%'.format(metrics.precision * 100.0, width=5, prec=2))

    def calculateMetrics(self):
        pass

    def stem(self, textToAnalyze):
        pass

    def analyze(self, textToAnalyze):
        pass